name: World Cup 1994
year: 1994
match_code: WC
cutoff: 1994-06-17
hosts:
- US
points:
  win: 2
  draw: 1
  loss: 0
tiebreakers:
- points
- gd
- gf
- h2h_points
- h2h_gd
- random
teams:
  US:
    name: United States
    elo: 1627
    elo_9m: 1649
  CH:
    name: Switzerland
    elo: 1859
    elo_9m: 1844
  CO:
    name: Colombia
    elo: 1885
    elo_9m: 1935
  RO:
    name: Romania
    elo: 1895
    elo_9m: 1785
  BR:
    name: Brazil
    elo: 1997
    elo_9m: 1944
  SE:
    name: Sweden
    elo: 1888
    elo_9m: 1890
  RU:
    name: Russia
    elo: 1834
    elo_9m: 1863
  CM:
    name: Cameroon
    elo: 1701
    elo_9m: 1626
  DE:
    name: Germany
    elo: 2018
    elo_9m: 2011
  ES:
    name: Spain
    elo: 1876
    elo_9m: 1855
  KR:
    name: South Korea
    elo: 1683
    elo_9m: 1629
  BO:
    name: Bolivia
    elo: 1694
    elo_9m: 1707
  AR:
    name: Argentina
    elo: 1939
    elo_9m: 1908
  NG:
    name: Nigeria
    elo: 1793
    elo_9m: 1697
  BG:
    name: Bulgaria
    elo: 1714
    elo_9m: 1756
  GR:
    name: Greece
    elo: 1664
    elo_9m: 1716
  IT:
    name: Italy
    elo: 1947
    elo_9m: 1985
  IE:
    name: Ireland
    elo: 1904
    elo_9m: 1846
  NO:
    name: Norway
    elo: 1881
    elo_9m: 1846
  MX:
    name: Mexico
    elo: 1825
    elo_9m: 1893
  BE:
    name: Belgium
    elo: 1841
    elo_9m: 1850
  NL:
    name: Netherlands
    elo: 1998
    elo_9m: 1962
  SA:
    name: Saudi Arabia
    elo: 1630
    elo_9m: 1623
  MA:
    name: Morocco
    elo: 1649
    elo_9m: 1644
stages:
- id: groups
  type: groups
  groups:
    A:
    - RO
    - CH
    - US
    - CO
    B:
    - BR
    - SE
    - RU
    - CM
    C:
    - DE
    - ES
    - KR
    - BO
    D:
    - NG
    - BG
    - AR
    - GR
    E:
    - MX
    - IE
    - IT
    - NO
    F:
    - NL
    - SA
    - BE
    - MA
  schedule:
  - - 1994-06-17
    - C
    - DE
    - BO
    - 1
    - 0
  - - 1994-06-17
    - C
    - ES
    - KR
    - 2
    - 2
  - - 1994-06-18
    - E
    - IE
    - IT
    - 1
    - 0
  - - 1994-06-18
    - A
    - RO
    - CO
    - 3
    - 1
  - - 1994-06-18
    - A
    - CH
    - US
    - 1
    - 1
  - - 1994-06-19
    - F
    - BE
    - MA
    - 1
    - 0
  - - 1994-06-19
    - B
    - SE
    - CM
    - 2
    - 2
  - - 1994-06-19
    - E
    - MX
    - NO
    - 0
    - 1
  - - 1994-06-20
    - B
    - BR
    - RU
    - 2
    - 0
  - - 1994-06-20
    - F
    - NL
    - SA
    - 2
    - 1
  - - 1994-06-21
    - D
    - AR
    - GR
    - 4
    - 0
  - - 1994-06-21
    - C
    - DE
    - ES
    - 1
    - 1
  - - 1994-06-21
    - D
    - NG
    - BG
    - 3
    - 0
  - - 1994-06-22
    - A
    - RO
    - CH
    - 1
    - 4
  - - 1994-06-22
    - A
    - US
    - CO
    - 2
    - 1
  - - 1994-06-23
    - C
    - KR
    - BO
    - 0
    - 0
  - - 1994-06-23
    - E
    - IT
    - NO
    - 1
    - 0
  - - 1994-06-24
    - B
    - BR
    - CM
    - 3
    - 0
  - - 1994-06-24
    - E
    - MX
    - IE
    - 2
    - 1
  - - 1994-06-24
    - B
    - SE
    - RU
    - 3
    - 1
  - - 1994-06-25
    - D
    - NG
    - AR
    - 1
    - 2
  - - 1994-06-25
    - F
    - NL
    - BE
    - 0
    - 1
  - - 1994-06-25
    - F
    - SA
    - MA
    - 2
    - 1
  - - 1994-06-26
    - D
    - BG
    - GR
    - 4
    - 0
  - - 1994-06-26
    - A
    - CH
    - CO
    - 0
    - 2
  - - 1994-06-26
    - A
    - RO
    - US
    - 1
    - 0
  - - 1994-06-27
    - C
    - DE
    - KR
    - 3
    - 2
  - - 1994-06-27
    - C
    - ES
    - BO
    - 3
    - 1
  - - 1994-06-28
    - B
    - BR
    - SE
    - 1
    - 1
  - - 1994-06-28
    - E
    - IE
    - NO
    - 0
    - 0
  - - 1994-06-28
    - E
    - MX
    - IT
    - 1
    - 1
  - - 1994-06-28
    - B
    - RU
    - CM
    - 6
    - 1
  - - 1994-06-29
    - F
    - NL
    - MA
    - 2
    - 1
  - - 1994-06-29
    - F
    - SA
    - BE
    - 1
    - 0
  - - 1994-06-30
    - D
    - BG
    - AR
    - 2
    - 0
  - - 1994-06-30
    - D
    - NG
    - GR
    - 2
    - 0
- id: r16
  type: bracket
  matches:
    m1:
      home: groups.D.1
      away: groups.E.3
      date: 1994-07-05
      actual:
        winner: IT
        score:
        - 1
        - 2
    m2:
      home: groups.F.2
      away: groups.B.2
      date: 1994-07-03
      actual:
        winner: SE
        score:
        - 1
        - 3
    m3:
      home: groups.A.1
      away: groups.D.3
      date: 1994-07-03
      actual:
        winner: RO
        score:
        - 3
        - 2
    m4:
      home: groups.D.2
      away: groups.E.1
      date: 1994-07-05
      actual:
        winner: BG
        score:
        - 1
        - 1
    m5:
      home: groups.B.1
      away: groups.A.3
      date: 1994-07-04
      actual:
        winner: BR
        score:
        - 1
        - 0
    m6:
      home: groups.C.1
      away: groups.F.3
      date: 1994-07-02
      actual:
        winner: DE
        score:
        - 3
        - 2
    m7:
      home: groups.F.1
      away: groups.E.2
      date: 1994-07-04
      actual:
        winner: NL
        score:
        - 2
        - 0
    m8:
      home: groups.C.2
      away: groups.A.2
      date: 1994-07-02
      actual:
        winner: ES
        score:
        - 3
        - 0
- id: qf
  type: bracket
  matches:
    qf1:
      home: r16.m1.W
      away: r16.m8.W
      date: 1994-07-09
      actual:
        winner: IT
        score:
        - 2
        - 1
    qf2:
      home: r16.m4.W
      away: r16.m6.W
      date: 1994-07-10
      actual:
        winner: BG
        score:
        - 2
        - 1
    qf3:
      home: r16.m5.W
      away: r16.m7.W
      date: 1994-07-09
      actual:
        winner: BR
        score:
        - 3
        - 2
    qf4:
      home: r16.m2.W
      away: r16.m3.W
      date: 1994-07-10
      actual:
        winner: SE
        score:
        - 2
        - 2
- id: sf
  type: bracket
  matches:
    sf1:
      home: qf.qf1.W
      away: qf.qf2.W
      date: 1994-07-13
      actual:
        winner: IT
        score:
        - 2
        - 1
    sf2:
      home: qf.qf3.W
      away: qf.qf4.W
      date: 1994-07-13
      actual:
        winner: BR
        score:
        - 1
        - 0
- id: third_place
  type: match
  home: sf.sf1.L
  away: sf.sf2.L
  date: 1994-07-16
  actual:
    winner: SE
    score:
    - 0
    - 4
- id: final
  type: match
  home: sf.sf1.W
  away: sf.sf2.W
  date: 1994-07-17
  actual:
    winner: BR
    score:
    - 0
    - 0
